services:
  # nest-admin-web:
  #   image: buqiyuan/vue3-antdv-admin:stable
  #   container_name: nest-admin-web
  #   volumes:
  #     - ./deploy/web:/etc/nginx/conf.d
  #   ports:
  #     - '10010:80'
  #   restart: always
  #   networks:
  #     - nest_admin_net
  redis:
    image: redis:7.4.0-alpine
    ports:
      - 20241:6379
    restart: always

  mongodb:
    image: mongo:8.0.0
    ports:
      - 20242:27017
    restart: always
    healthcheck:
      test: echo 'db.state().ok' | mongosh localhost:20241/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - "./db/mongodb:/data/db"
      - "./conf/initdb.d/mongo:/docker-entrypoint-initdb.d"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 20243:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data/pgdata
      - ./conf/initdb.d/postgres:/docker-entrypoint-initdb.d
networks:
  fast-api-networks:
    external: true
  
      
  

  # mysql:
  #   image: mysql:latest
  #   container_name: nextjs-fastapi
  #   restart: always
  #   # env_file:
  #   #   - .env
  #   environment:
  #     - MYSQL_HOST=127.0.0.1
  #     - MYSQL_PORT=23306
  #     - MYSQL_DATABASE=FastAPI
  #     - MYSQL_USERNAME=root
  #     - MYSQL_PASSWORD=Qwer1234
  #     - MYSQL_ROOT_PASSWORD=Qwer1234

  #   ports:
  #     - '23306:3306'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
  #   # volumes:
  #   # - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
  #   # - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本

  # nest-admin-server:
  # build: 从当前路径构建镜像
  # build:
  #   context: .
  #   dockerfile: Dockerfile
  #   args:
  #     - PROJECT_DIR=${PROJECT_DIR}
  # image: buqiyuan/nest-admin-server:stable
  # container_name: nest-admin-server
  # restart: always
  # env_file:
  #   - .env
  #   - .env.production
  # extra_hosts:
  #   - 'host.docker.internal:host-gateway'
  # ports:
  #   - '${APP_PORT}:${APP_PORT}'
  # volumes:
  #   - ./logs/:${PROJECT_DIR}/logs/ # ./logs 日志文件挂载到容器外部
  # # 当前服务启动之前先要把depends_on指定的服务启动起来才行
  # depends_on:
  #   - mysql
  #   - redis
  # networks:
  #   - nest_admin_net

# volumes:
#   nest-mysql:
#     name: nest-mysql-db

# networks:
#   nest_admin_net:
#     name: nest_admin_net
#     # driver: custom-driver-1

