// This file is auto-generated by @hey-api/openapi-ts

export type Body_loginForm_api_login_form_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_update_item_api_demo_items2__item_id__put = {
    item: Item;
    user: User_Input;
    importance: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Item = {
    name: string;
    description?: string | null;
    price: number;
    tax?: number | null;
};

export type LoginModel = {
    username: string;
    password: string;
    scopes?: Array<(string)>;
};

/**
 * Represents a Post record
 */
export type Post = {
    id: number;
    created_at: string;
    updated_at: string;
    title: string;
    published: boolean;
    author?: User_Output | null;
    author_id?: number | null;
};

export type PostCreateManyNestedWithoutRelationsInput = {
    create?: PostCreateWithoutRelationsInput | Array<PostCreateWithoutRelationsInput>;
    connect?: _PostWhereUnique_id_Input | Array<_PostWhereUnique_id_Input>;
};

/**
 * Required arguments to the Post create method, without relations
 */
export type PostCreateWithoutRelationsInput = {
    id?: number;
    created_at?: string;
    updated_at?: string;
    author_id?: number | null;
    title: string;
    published: boolean;
};

export type PostUpdateManyWithoutRelationsInput = {
    create?: Array<PostCreateWithoutRelationsInput>;
    connect?: Array<_PostWhereUnique_id_Input>;
    set?: Array<_PostWhereUnique_id_Input>;
    disconnect?: Array<_PostWhereUnique_id_Input>;
    delete?: Array<_PostWhereUnique_id_Input>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type User_Input = {
    username: string;
    full_name?: string | null;
};

/**
 * Represents a User record
 */
export type User_Output = {
    id: number;
    username: string;
    hashed_password: string;
    email?: string | null;
    disabled: boolean;
    posts?: Array<Post> | null;
};

export type UserCreate = {
    username: string;
    password: string;
    email?: string | null;
};

/**
 * Required arguments to the User create method
 */
export type UserCreateInput = {
    id?: number;
    email?: string | null;
    disabled?: boolean;
    posts?: PostCreateManyNestedWithoutRelationsInput;
    username: string;
    hashed_password: string;
};

/**
 * Optional arguments for updating a record
 */
export type UserUpdateInput = {
    id?: _IntSetInput | _IntDivideInput | _IntMultiplyInput | _IntIncrementInput | _IntDecrementInput | number;
    username?: string;
    hashed_password?: string;
    email?: string | null;
    disabled?: boolean;
    posts?: PostUpdateManyWithoutRelationsInput;
};

export type UserWihoutPassword = {
    id: number;
    username: string;
    email?: string | null;
};

export type UserWithoutRelations = {
    id: number;
    username: string;
    hashed_password: string;
    email?: string | null;
};

export type UsersList = {
    list: Array<UserWihoutPassword>;
    total: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type _IntDecrementInput = {
    decrement: number;
};

export type _IntDivideInput = {
    divide: number;
};

export type _IntIncrementInput = {
    increment: number;
};

export type _IntMultiplyInput = {
    multiply: number;
};

export type _IntSetInput = {
    set: number;
};

export type _PostWhereUnique_id_Input = {
    id: number;
};

export type LoginFormApiLoginFormPostData = {
    body: Body_loginForm_api_login_form_post;
};

export type LoginFormApiLoginFormPostResponse = Token;

export type LoginFormApiLoginFormPostError = HTTPValidationError;

export type LoginApiLoginPostData = {
    body: LoginModel;
};

export type LoginApiLoginPostResponse = Token;

export type LoginApiLoginPostError = HTTPValidationError;

export type ReadUsersMeApiUserMeGetResponse = User_Output;

export type ReadUsersMeApiUserMeGetError = unknown;

export type ReadOwnItemsApiUserMeItemsGetResponse = Array<{
    [key: string]: (string);
}>;

export type ReadOwnItemsApiUserMeItemsGetError = unknown;

export type ListUsersApiUserGetData = {
    query?: {
        skip?: number;
        take?: number;
    };
};

export type ListUsersApiUserGetResponse = UsersList;

export type ListUsersApiUserGetError = HTTPValidationError;

export type CreateUserApiUserPostData = {
    body: UserCreate;
};

export type CreateUserApiUserPostResponse = User_Output;

export type CreateUserApiUserPostError = HTTPValidationError;

export type GetUserApiUserUserIdGetData = {
    path: {
        user_id: number;
    };
};

export type GetUserApiUserUserIdGetResponse = UserWihoutPassword | null;

export type GetUserApiUserUserIdGetError = HTTPValidationError;

export type UpdateUserApiUserUserIdPutData = {
    body: UserUpdateInput;
    path: {
        user_id: number;
    };
};

export type UpdateUserApiUserUserIdPutResponse = UserWithoutRelations;

export type UpdateUserApiUserUserIdPutError = HTTPValidationError;

export type DeleteUserApiUserUserIdDeleteData = {
    path: {
        user_id: number;
    };
};

export type DeleteUserApiUserUserIdDeleteResponse = User_Output;

export type DeleteUserApiUserUserIdDeleteError = HTTPValidationError;

export type RootApiStreamGetResponse = unknown;

export type RootApiStreamGetError = unknown;

export type ReadRootApiDemoGetResponse = unknown;

export type ReadRootApiDemoGetError = unknown;

export type ReadItemApiDemoItemsItemIdGetData = {
    path: {
        item_id: number;
    };
    query?: {
        q?: string | null;
    };
};

export type ReadItemApiDemoItemsItemIdGetResponse = unknown;

export type ReadItemApiDemoItemsItemIdGetError = HTTPValidationError;

export type UpdateItem12ApiDemoItemsItemIdPutData = {
    body: Item;
    path: {
        item_id: number;
    };
    query?: {
        q?: string | null;
    };
};

export type UpdateItem12ApiDemoItemsItemIdPutResponse = unknown;

export type UpdateItem12ApiDemoItemsItemIdPutError = HTTPValidationError;

export type CreateItemApiDemoItemsPostData = {
    body: Item;
};

export type CreateItemApiDemoItemsPostResponse = unknown;

export type CreateItemApiDemoItemsPostError = HTTPValidationError;

export type UpdateItemApiDemoItems2ItemIdPutData = {
    body: Body_update_item_api_demo_items2__item_id__put;
    path: {
        item_id: number;
    };
};

export type UpdateItemApiDemoItems2ItemIdPutResponse = unknown;

export type UpdateItemApiDemoItems2ItemIdPutError = HTTPValidationError;

export type ReadItemsApiDemoItems3QueryGetData = {
    query?: {
        q?: string | null;
    };
};

export type ReadItemsApiDemoItems3QueryGetResponse = unknown;

export type ReadItemsApiDemoItems3QueryGetError = HTTPValidationError;

export type ReadItems2ApiDemoItems3DefaultGetData = {
    query: {
        q: string;
    };
};

export type ReadItems2ApiDemoItems3DefaultGetResponse = unknown;

export type ReadItems2ApiDemoItems3DefaultGetError = HTTPValidationError;

export type ReadItemsDepApiDemoDepGetData = {
    query?: {
        limit?: number;
        q?: string | null;
        skip?: number;
    };
};

export type ReadItemsDepApiDemoDepGetResponse = unknown;

export type ReadItemsDepApiDemoDepGetError = HTTPValidationError;

export type ReadItemsDep22ApiDemoDep2GetData = {
    headers: {
        'x-token': string;
    };
    query?: {
        limit?: number;
        q?: string | null;
        skip?: number;
    };
};

export type ReadItemsDep22ApiDemoDep2GetResponse = unknown;

export type ReadItemsDep22ApiDemoDep2GetError = HTTPValidationError;

export type ListUsersApiPrismaUserGetData = {
    query?: {
        skip?: number;
        take?: number;
    };
};

export type ListUsersApiPrismaUserGetResponse = UsersList;

export type ListUsersApiPrismaUserGetError = HTTPValidationError;

export type CreateUserApiPrismaUserPostData = {
    body: UserCreateInput;
};

export type CreateUserApiPrismaUserPostResponse = UserWithoutRelations;

export type CreateUserApiPrismaUserPostError = HTTPValidationError;

export type UpdateUserByidApiPrismaUserPutData = {
    body: UserUpdateInput;
};

export type UpdateUserByidApiPrismaUserPutResponse = UserWithoutRelations;

export type UpdateUserByidApiPrismaUserPutError = HTTPValidationError;

export type GetUserApiPrismaUserUserIdGetData = {
    path: {
        user_id: number;
    };
};

export type GetUserApiPrismaUserUserIdGetResponse = UserWithoutRelations | null;

export type GetUserApiPrismaUserUserIdGetError = HTTPValidationError;

export type UpdateUserApiPrismaUserUserIdPutData = {
    body: UserUpdateInput;
    path: {
        user_id: number;
    };
};

export type UpdateUserApiPrismaUserUserIdPutResponse = UserWithoutRelations;

export type UpdateUserApiPrismaUserUserIdPutError = HTTPValidationError;

export type DeleteUserApiPrismaUserUserIdDeleteData = {
    path: {
        user_id: number;
    };
};

export type DeleteUserApiPrismaUserUserIdDeleteResponse = User_Output;

export type DeleteUserApiPrismaUserUserIdDeleteError = HTTPValidationError;

export type $OpenApiTs = {
    '/api/login-form': {
        post: {
            req: LoginFormApiLoginFormPostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': Token;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/login': {
        post: {
            req: LoginApiLoginPostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': Token;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/user/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                '200': User_Output;
            };
        };
    };
    '/api/user/me/items': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                '200': Array<{
                    [key: string]: (string);
                }>;
            };
        };
    };
    '/api/user': {
        get: {
            req: ListUsersApiUserGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UsersList;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        post: {
            req: CreateUserApiUserPostData;
            res: {
                /**
                 * Successful Response
                 */
                '201': User_Output;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/user/{user_id}': {
        get: {
            req: GetUserApiUserUserIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UserWihoutPassword | null;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        put: {
            req: UpdateUserApiUserUserIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UserWithoutRelations;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        delete: {
            req: DeleteUserApiUserUserIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                '200': User_Output;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/stream': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
            };
        };
    };
    '/api/demo': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
            };
        };
    };
    '/api/demo/items/{item_id}': {
        get: {
            req: ReadItemApiDemoItemsItemIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        put: {
            req: UpdateItem12ApiDemoItemsItemIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/demo/items': {
        post: {
            req: CreateItemApiDemoItemsPostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/demo/items2/{item_id}': {
        put: {
            req: UpdateItemApiDemoItems2ItemIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/demo/items3/query': {
        get: {
            req: ReadItemsApiDemoItems3QueryGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/demo/items3/default': {
        get: {
            req: ReadItems2ApiDemoItems3DefaultGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/demo/dep/': {
        get: {
            req: ReadItemsDepApiDemoDepGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/demo/dep2/': {
        get: {
            req: ReadItemsDep22ApiDemoDep2GetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/prisma/user': {
        get: {
            req: ListUsersApiPrismaUserGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UsersList;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        post: {
            req: CreateUserApiPrismaUserPostData;
            res: {
                /**
                 * Successful Response
                 */
                '201': UserWithoutRelations;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        put: {
            req: UpdateUserByidApiPrismaUserPutData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UserWithoutRelations;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/prisma/user/{user_id}': {
        get: {
            req: GetUserApiPrismaUserUserIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UserWithoutRelations | null;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        put: {
            req: UpdateUserApiPrismaUserUserIdPutData;
            res: {
                /**
                 * Successful Response
                 */
                '200': UserWithoutRelations;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        delete: {
            req: DeleteUserApiPrismaUserUserIdDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                '200': User_Output;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
};